# Generated by Django 3.0.2 on 2020-01-27 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('version', models.CharField(max_length=50)),
                ('upstream_state', models.IntegerField(choices=[(0, 'Up To Date'), (1, 'Update Available'), (2, 'Only Upstream')])),
                ('local_state', models.IntegerField(choices=[(0, 'In Progress'), (1, 'Queued'), (2, 'Up To Date')])),
            ],
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_dependency', models.BooleanField()),
                ('run_dependency', models.BooleanField()),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends', to='packages.Package')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdepends', to='packages.Package')),
            ],
            options={
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
