# Generated by Django 3.0.2 on 2020-01-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='local_state',
            field=models.IntegerField(choices=[(0, 'In Progress'), (1, 'Queued'), (2, 'Up To Date')], default=2),
        ),
        migrations.AlterField(
            model_name='package',
            name='upstream_state',
            field=models.IntegerField(choices=[(0, 'Up To Date'), (1, 'Update Available'), (2, 'Only Upstream'), (3, 'Unknown')], default=3),
        ),
    ]
