# Generated by Django 3.0.2 on 2020-01-28 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_auto_20200127_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
