# Generated by Django 3.0.2 on 2020-01-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20200128_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='upstream_state',
            field=models.IntegerField(choices=[(0, 'Update Available'), (1, 'Up To Date'), (2, 'Only Upstream'), (3, 'Unknown')], default=3),
        ),
    ]
